### PR TITLE
ERC721 and ERC1155 support

### PR DESCRIPTION
**Pull request by tuler**
Add support for ERC721 and ERC1155.
Breaking change: change balanceOf to explicit etherBalanceOf and erc20BalanceOf

This implementation follows the same design pattern of the support of ether and ERC20.

Test has 100% coverage now.

To run tests, there is an issue with `vitest` not supporting import assertion.
So the best I could do for now was to comment out the `assert { type: "json" }` from `packages/wallet/wagmi.config.ts` so `pnpm run test` works.

### CODE REVIEW

**Comment by tuler** [comment]
Still missing batch transfer of ERC1155 and batch withdraw of ERC1155.
Will work on that

**Comment by tuler** [comment]
Batch operations of ERC1155 implemented.

**Comment by tuler** [comment]
Problem of running test fixed

**Comment by fabiooshiro** [comment]
I prefer balanceOfEther.
Not a big deal

**Comment by tuler** [comment]
> I prefer balanceOfEther.

I agree it's a little strange, but the context is:

The name of the method was a reflection of the name of the ERC20 method, [balanceOf(account)](https://docs.openzeppelin.com/contracts/5.x/api/token/erc20#IERC20-balanceOf-address-)
So it's `of` account, not `of` erc20

To be fair ERC71 also has a [balanceOf(owner)](https://docs.openzeppelin.com/contracts/5.x/api/token/erc721#IERC721-balanceOf-address-) which we don't have.

**Review by sandhilt — APPROVED** [review]

**Pull request merged**
